from . import hr_person
from . import hr_doctor
from . import hr_patient
from . import hr_contact_person
from . import hr_doctor_schedule
from . import hr_patient_visit
from . import hr_disease
from . import hr_diagnosis
from . import hr_history_changing_doctor
from . import hr_analysis
