# -*- coding: utf-8 -*-
from . import res_partner
from . import tour_reservation
from . import tour_reservation_booking
from . import service
from . import accomodation
from . import flight
from . import ferry
from . import day_sheet
from . import account_invoice
from . import res_config_settings
from . import transfer_excursion
from . import account
from . import itinerary
from . import tour
from . import travel_information
from . import sale_order
from . import tour_visa
from . import tour_dashboard
from . import accomodation_information
from . import custom_booking_information
from . import insurance
from . import agent_commission
from . import tour_pricelist
